name: Chad Trim
favicon: null
layout_spectrum: 0.8111511529423296
typography_spectrum: 0.02212343900464475
title: Chad Trim
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.24194115307182074
  lightness: 0.7583475520368665
  saturation: 0.33410282782278955
  rhythmicContrast: 0.05970125272870064
purpose: []
